#include "../include/graph.h"

static const char *colors[9] = {"red", "dark-green", "orange", "blue", "purple", "dark-cyan", "grey", "brown", "dark-pink"};

// Number of generated graphs
static int count = 1;

#define DEFINE_GRAPH(BIT)                                                                                                                 \
    /*                                                                                                                                    \
     * Contains the data generated by the benchmark.                                                                                      \
     * Avoid regenerating data from the same algorithm.                                                                                   \
     * Each pointer corresponds to an algorithm.                                                                                          \
     * If an algorithm is not used, then its pointer is NULL.                                                                             \
     */                                                                                                                                   \
    static double **data_tab##BIT = NULL;                                                                                                 \
                                                                                                                                          \
    /*                                                                                                                                    \
     * All algorithms to be tested must compute the same vectors.                                                                         \
     */                                                                                                                                   \
    static struct                                                                                                                         \
    {                                                                                                                                     \
        vector##BIT##_t *vectors;                                                                                                         \
        ulong size;                                                                                                                       \
    } vector_sample##BIT = {.vectors = NULL};                                                                                             \
                                                                                                                                          \
    int init_data_tab##BIT(void)                                                                                                          \
    {                                                                                                                                     \
        if (data_tab##BIT == NULL)                                                                                                        \
        {                                                                                                                                 \
            data_tab##BIT = calloc(NB_ALGO, sizeof(double *));                                                                            \
            if (data_tab##BIT == NULL)                                                                                                    \
            {                                                                                                                             \
                perror("init_data_tab data_tab calloc");                                                                                  \
                return 1;                                                                                                                 \
            }                                                                                                                             \
        }                                                                                                                                 \
        return 0;                                                                                                                         \
    }                                                                                                                                     \
                                                                                                                                          \
    void free_data_tab##BIT(void)                                                                                                         \
    {                                                                                                                                     \
        if (data_tab##BIT != NULL)                                                                                                        \
        {                                                                                                                                 \
            for (int i = 0; i < NB_ALGO; i++)                                                                                             \
                free(*(data_tab##BIT + i));                                                                                               \
            free(data_tab##BIT);                                                                                                          \
        }                                                                                                                                 \
        vector##BIT##_t *vectors = vector_sample##BIT.vectors;                                                                            \
        if (vectors != NULL)                                                                                                              \
        {                                                                                                                                 \
            for (ulong i = 0; i < vector_sample##BIT.size; i++)                                                                           \
                free_vector(*(vectors + i));                                                                                              \
            free(vectors);                                                                                                                \
        }                                                                                                                                 \
    }                                                                                                                                     \
                                                                                                                                          \
    static int benchmark##BIT(int fd, int scale, ulong nb_points, param##BIT##_t param, const AlgorithmID algorithm_ids[], int nb_algo)   \
    {                                                                                                                                     \
        if (vector_sample##BIT.vectors == NULL)                                                                                           \
        {                                                                                                                                 \
            vector_sample##BIT.vectors = malloc(nb_points * sizeof(vector##BIT##_t));                                                     \
            vector_sample##BIT.size = nb_points;                                                                                          \
            if (vector_sample##BIT.vectors == NULL)                                                                                       \
            {                                                                                                                             \
                perror("benchmark vector_sample malloc");                                                                                 \
                return 1;                                                                                                                 \
            }                                                                                                                             \
            for (ulong i = 0; i < nb_points; i++)                                                                                         \
                *(vector_sample##BIT.vectors + i) = rand_vector##BIT((i + 1) * scale);                                                    \
        }                                                                                                                                 \
        for (int i = 0; i < nb_algo; i++)                                                                                                 \
        {                                                                                                                                 \
            AlgorithmID id = algorithm_ids[i];                                                                                            \
                                                                                                                                          \
            /* If it is the first time that the algorithm is tested: calculate the time taken */                                          \
            if (*(data_tab##BIT + id) == NULL)                                                                                            \
            {                                                                                                                             \
                *(data_tab##BIT + id) = malloc(nb_points * sizeof(double));                                                               \
                if (*(data_tab##BIT + id) == NULL)                                                                                        \
                {                                                                                                                         \
                    perror("benchmark *(data_tab + id) malloc");                                                                          \
                    return 1;                                                                                                             \
                }                                                                                                                         \
                for (ulong j = 0; j < nb_points; j++)                                                                                     \
                    *(*(data_tab##BIT + id) + j) = time_algorithm(algorithms##BIT[id].address, param, *(vector_sample##BIT.vectors + j)); \
            }                                                                                                                             \
                                                                                                                                          \
            /* Writes on the output file */                                                                                               \
            for (ulong j = 0; j < nb_points; j++)                                                                                         \
                dprintf(fd, "%lu,%.20f\n", (j + 1) * scale, *(*(data_tab##BIT + id) + j));                                                \
            dprintf(fd, "e\n");                                                                                                           \
        }                                                                                                                                 \
        return 0;                                                                                                                         \
    }                                                                                                                                     \
                                                                                                                                          \
    int generate_graph(int scale, ulong nb_points, param##BIT##_t param, const AlgorithmID algorithm_ids[], int nb_algo)                  \
    {                                                                                                                                     \
        /* Creation of the directory */                                                                                                   \
        mkdir("graphs", 0755);                                                                                                            \
        char file_name[32];                                                                                                               \
        snprintf(file_name, sizeof(file_name) - 1, "graphs/graph%d.gp", count);                                                           \
        int fd = open(file_name, O_CREAT | O_WRONLY | O_TRUNC, 0644);                                                                     \
        if (fd == -1)                                                                                                                     \
        {                                                                                                                                 \
            perror("generate_curve fd open");                                                                                             \
            return 1;                                                                                                                     \
        }                                                                                                                                 \
                                                                                                                                          \
        /* Header */                                                                                                                      \
        dprintf(fd, "set terminal pngcairo size 1200,800 enhanced font 'arial,10'\n"                                                      \
                    "set datafile separator ','\n"                                                                                        \
                    "set key outside\n"                                                                                                   \
                    "set title 'Execution time for b = %u and p = %u'\n"                                                                  \
                    "set output 'graphs/graph%d.png'\n"                                                                                   \
                    "set xlabel 'Size of the vector'\n"                                                                                   \
                    "set ylabel 'Time in microseconds'\n"                                                                                 \
                    "plot ",                                                                                                              \
                param.b, param.p, count++);                                                                                               \
                                                                                                                                          \
        for (int i = 0; i < nb_algo; i++)                                                                                                 \
        {                                                                                                                                 \
            /* Header of the tested algorithms */                                                                                         \
            dprintf(fd, "'-' title '%s' with points pt 7 ps 0.25 linecolor '%s'", algorithms##BIT[algorithm_ids[i]].name, colors[i]);     \
            if (i < nb_algo - 1)                                                                                                          \
                dprintf(fd, ", ");                                                                                                        \
        }                                                                                                                                 \
        dprintf(fd, "\n");                                                                                                                \
                                                                                                                                          \
        int ret = 0;                                                                                                                      \
        if (benchmark##BIT(fd, scale, nb_points, param, algorithm_ids, nb_algo))                                                          \
        {                                                                                                                                 \
            perror("generate_curve benchmark");                                                                                           \
            ret = 1;                                                                                                                      \
            goto end;                                                                                                                     \
        }                                                                                                                                 \
        if (fork() == 0)                                                                                                                  \
        {                                                                                                                                 \
            /* Generation of the graph */                                                                                                 \
            execlp("gnuplot", "gnuplot", file_name, (char *)NULL);                                                                        \
                                                                                                                                          \
            perror("generate_curve execlp");                                                                                              \
            exit(1);                                                                                                                      \
        }                                                                                                                                 \
        int status;                                                                                                                       \
        wait(&status);                                                                                                                    \
        if (WIFEXITED(status))                                                                                                            \
            ret = WEXITSTATUS(status);                                                                                                    \
    end:                                                                                                                                  \
        close(fd);                                                                                                                        \
        return ret;                                                                                                                       \
    }

DEFINE_GRAPH(16)
DEFINE_GRAPH(32)
